# Generated by Django 6.1 on 2026-09-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terapeuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=191, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='terapeutas/fotos/')),
                ('certificado', models.FileField(blank=True, null=True, upload_to='terapeutas/certificados/')),
            ],
        ),
    ]
