# Generated by Django 6.1 on 2026-09-30 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terapeutaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='terapeuta',
            table='terapeutas',
        ),
    ]
