# Generated by Django 6.1 on 2026-10-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0002_alter_terapia_table'),
        ('terapeutaApp', '0002_alter_terapeuta_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='terapeuta',
            name='terapias',
            field=models.ManyToManyField(blank=True, related_name='terapeutas', to='adminApp.terapia', verbose_name='Terapias que realiza'),
        ),
    ]