# Generated by Django 6.1 on 2026-09-28 20:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminApp', '0001_initial'),
        ('terapeutaApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la Cita')),
                ('hora', models.TimeField(verbose_name='Hora de la Cita')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20, verbose_name='Estado de la Reserva')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Notas u Observaciones del Cliente')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservas', to='terapeutaApp.terapeuta', verbose_name='Terapeuta Asignado')),
                ('terapia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservas', to='adminApp.terapia', verbose_name='Terapia Seleccionada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_reservas', to=settings.AUTH_USER_MODEL, verbose_name='Cliente / Usuario')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reservas',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
