# Generated by Django 6.1 on 2026-09-30 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='terapia',
            table='terapias',
        ),
    ]
